return {
  normal = {
    { '🭽', 'FloatBorder' },
    { '▔', 'FloatBorder' },
    { '🭾', 'FloatBorder' },
    { '▕', 'FloatBorder' },
    { '🭿', 'FloatBorder' },
    { '▁', 'FloatBorder' },
    { '🭼', 'FloatBorder' },
    { '▏', 'FloatBorder' },
  },
  round = {
    { '╭', 'FloatBorder' },
    { '─', 'FloatBorder' },
    { '╮', 'FloatBorder' },
    { '│', 'FloatBorder' },
    { '╯', 'FloatBorder' },
    { '─', 'FloatBorder' },
    { '╰', 'FloatBorder' },
    { '│', 'FloatBorder' },
  },
  bold = {
    { '┏', 'FloatBorder' },
    { '─', 'FloatBorder' },
    { '┓', 'FloatBorder' },
    { '│', 'FloatBorder' },
    { '┛', 'FloatBorder' },
    { '─', 'FloatBorder' },
    { '┗', 'FloatBorder' },
    { '│', 'FloatBorder' },
  },
  plus = {
    { '+', 'FloatBorder' },
    { '─', 'FloatBorder' },
    { '+', 'FloatBorder' },
    { '│', 'FloatBorder' },
    { '+', 'FloatBorder' },
    { '─', 'FloatBorder' },
    { '+', 'FloatBorder' },
    { '│', 'FloatBorder' },
  },
}
