require("hop").setup()
vim.api.nvim_set_keymap("n", "s", ":HopChar1<cr>", { noremap = true, silent = false })
-- vim.api.nvim_set_keymap("n", "S", ":HopChar1BC<cr>", { noremap = true, silent = false })
vim.api.nvim_set_keymap("v", "s", [[<cmd> lua require'hop'.hint_char1()<cr>]], { noremap = true, silent = false })
vim.api.nvim_set_keymap("n", "gl", ":HopLine<cr>", { noremap = true, silent = false })
-- vim.api.nvim_set_keymap("n", "gL", ":HopLineBC<cr>", { noremap = true, silent = false })
vim.api.nvim_set_keymap("v", "gl", [[<cmd> lua require'hop'.hint_lines()<cr>]], { noremap = true, silent = false })
