#! /bin/bash

# launch sxhkd
~/.config/bspwm/scripts/launch_apps.sh "sxhkd"

bspc monitor eDP1 -d 1 2 3
bspc monitor VIRTUAL1 -d 4 5 6


bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_width 2
# bspc config focused_border_color "#9d7cd8"

xsetroot -cursor_name left_ptr

# launch polybar on primary monitor if it has not been started
if [[ -z $(pgrep -f -a "polybar -q primary") ]]; then
    polybar -r -q primary -c "~/.config/polybar/custom/config.ini" &
fi
if [[ -z $(pgrep -f -a "polybar -q secondary") ]]; then
    polybar -r -q secondary -c "~/.config/polybar/custom/config.ini" &
fi
  
# set wallpaper if x11vnc is not running
if [[ -z $(pgrep -a x11vnc) ]]; then
    ~/.fehbg
fi

# launch picom if x11vnc and picom is not running
# if [[ -z $(pgrep -a x11vnc) && -z $(pgrep -a picom) ]]; then
#     picom --experimental-backends &
# fi

# touchpad

# tapping
xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 0
# acceleration
xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.4
# two finger right click
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Click Method Enabled" 0 1

# move sticky window across monitors
# while bspc subscribe monitor_focus -c 1 > /dev/null; do
#     while bspc node 'any.!local.!hidden.sticky.window' -d focused -f; do
#         ~/.config/bspwm/scripts/change_display_properties.sh
#     done
# done

wmname compiz
touchegg &

# change border size according to window
pkill bspc
bspc subscribe node_focus | while read node; do
    focused_node=$(echo "$node" | awk '{print $4}')
    current_window_name=$(xdotool getwindowname "$focused_node")
    if [[ $current_window_name == scratchpad_terminal2 ]]; then
        # bspc config focused_border_color "#ebbcba"
        bspc config focused_border_color "#f7768e"
    else
        bspc config focused_border_color "#6e6a86"
        # bspc config focused_border_color "#ebbcba"
        # bspc config focused_border_color "#30c3ef"
    fi
done
