#! /bin/bash

if [[ -z $(pgrep -a sxhkd) ]]; then
    sxhkd -a Return &
fi

bspc monitor eDP1 -d 1 2 3
bspc monitor VIRTUAL1 -d 4 5 6

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty:kitty:scratchpad_terminal1 sticky=on state=floating
xsetroot -cursor_name left_ptr

# launch polybar on primary monitor if it has not been started
if [[ -z $(pgrep -f -a "polybar -q primary") ]]; then
    polybar -q primary -c "~/.config/polybar/custom/config.ini" &
fi

# set wallpaper if x11vnc is not running
if [[ -z $(pgrep -a x11vnc) ]]; then
    ~/.fehbg
fi

# launch picom if x11vnc and picom is not running
if [[ -z $(pgrep -a x11vnc) && -z $(pgrep -a picom) ]]; then
    picom --experimental-backends &
fi

# touchpad
xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 0
xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.8

# move sticky window across monitors
# while bspc subscribe monitor_focus -c 1 > /dev/null; do
#     while bspc node 'any.!local.!hidden.sticky.window' -d focused -f; do
#         ~/.config/bspwm/scripts/change_display_properties.sh
#     done
# done
